"""init

Revision ID: 9c176fa9e70d
Revises: 3b381ddf2002
Create Date: 2019-06-28 19:16:58.529304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c176fa9e70d'
down_revision = '3b381ddf2002'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('association')
    op.drop_table('association2')
    op.add_column('players', sa.Column('password_hash', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'password_hash')
    op.create_table('association2',
    sa.Column('match_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], name='association2_match_id_fkey'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name='association2_team_id_fkey')
    )
    op.create_table('association',
    sa.Column('player_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name='association_event_id_fkey'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name='association_player_id_fkey')
    )
    # ### end Alembic commands ###
