"""init

Revision ID: 3b381ddf2002
Revises: 915dbec21027
Create Date: 2019-06-27 18:20:11.339517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b381ddf2002'
down_revision = '915dbec21027'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('type_of_event', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events')),
    sa.UniqueConstraint('name', name=op.f('uq_events_name'))
    )
    op.create_index('event_index', 'events', ['id'], unique=True, mysql_length=255)
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teams')),
    sa.UniqueConstraint('name', name=op.f('uq_teams_name'))
    )
    op.create_index('team_index', 'teams', ['id'], unique=True, mysql_length=255)
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_matches_event_id_events')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_matches')),
    sa.UniqueConstraint('name', name=op.f('uq_matches_name'))
    )
    op.create_index('match_index', 'matches', ['id'], unique=True, mysql_length=255)
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('surname', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('imageurl', sa.Text(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('telephone', sa.Text(), nullable=True),
    sa.Column('ratings_by_own', sa.JSON(), nullable=True),
    sa.Column('rating_evaluation', sa.FLOAT(), nullable=True),
    sa.Column('credit', sa.FLOAT(), nullable=True),
    sa.Column('role_preference', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_players_team_id_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_players')),
    sa.UniqueConstraint('username', name=op.f('uq_players_username'))
    )
    op.create_index('player_index', 'players', ['id'], unique=True, mysql_length=255)
    op.create_table('match_team',
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], name=op.f('fk_match_team_match_id_matches')),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_match_team_team_id_teams'))
    )
    op.create_table('player_event',
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_player_event_event_id_events')),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_player_event_player_id_players'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_event')
    op.drop_table('match_team')
    op.drop_index('player_index', table_name='players')
    op.drop_table('players')
    op.drop_index('match_index', table_name='matches')
    op.drop_table('matches')
    op.drop_index('team_index', table_name='teams')
    op.drop_table('teams')
    op.drop_index('event_index', table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
