"""init

Revision ID: 5268a5b367cf
Revises: 9c176fa9e70d
Create Date: 2019-07-08 01:44:02.493770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5268a5b367cf'
down_revision = '9c176fa9e70d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('association')
    op.drop_table('association2')
    op.add_column('events', sa.Column('date', sa.DATE(), nullable=True))
    op.add_column('events', sa.Column('location', sa.Text(), nullable=True))
    op.add_column('events', sa.Column('time', sa.TIME(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'time')
    op.drop_column('events', 'location')
    op.drop_column('events', 'date')
    op.create_table('association2',
    sa.Column('match_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], name='association2_match_id_fkey'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name='association2_team_id_fkey')
    )
    op.create_table('association',
    sa.Column('player_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name='association_event_id_fkey'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name='association_player_id_fkey')
    )
    # ### end Alembic commands ###
