"""init

Revision ID: 915dbec21027
Revises: b3dee85ca418
Create Date: 2019-06-27 17:43:48.901073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '915dbec21027'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
